### PR TITLE
Make select component screen reader friendly

### PR DESCRIPTION
**Pull request by tylertrotter**
This PR does 3 main things:

1. For single-select components, values are instantly selected when navigating with the arrow keys. This mirrors the behavior of native selects and also automatically fixes the screen reader problem without having to do anything else. Compare: https://codepen.io/tylertrotter/pen/xxKVJpO

2. The above approach won't work for multi-select components so the non-screen reader behavior remains unchanged and many aria attributes are added to get screen readers to work. This was my exemplar: https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html

3. Removes marking deselected select components as "readonly." I don't know why this was ever needed. Before, when the transition to readonly happened (on blur of select) the NVDA screen reader would read out "read-only", which was very distracting. Not setting it to readonly also allows the select to be focused upon click of its label (which is a requirement).

### CODE REVIEW

**Comment by mattheyan** [comment]
@tylertrotter Do you already have a PR in element for this, or are you planning on doing that later?

**Comment by tylertrotter** [comment]
@mattheyan My understanding is that that would be the very last step. Even after this code has been through QA and released.

**Comment by mattheyan** [comment]
@tylertrotter We can do it either way, its fine that we haven't opened a PR with them, just wondering. There's a lot here, so I may want to sit down with you and go over these changes at some point when you have time.

**Comment by mattheyan** [comment]
Summary of our conversation:
- PR with just aria attributes, etc.
- Submit PR to element for removing `disabled`
- Tackle making select behave like native separately
  - Don't fire change immediately
  - Show value in input as you move around
  - Fire change when blurred, no matter how (even escape)

**Comment by mattheyan** [comment]
For simplicity we could just go ahead and make the `disabled` change in our fork, then if the element PR results in the change not being integrated we can override it in our code base. Probably best to submit PRs separately though, if it makes sense to do that, so the disabled change doesn't jeopardize the others?

**Comment by mattheyan** [comment]
Reminder:
[ ] Add the `selected` resource to our Hindi language file

**Pull request closed without merging**
