### PR TITLE
Select: Add 'filterMatch' option to control filtering behavior

### PR DESCRIPTION
**Pull request by mattheyan**
We have the requirement that when you filter some select fields, it should only match text that *starts with* the typed text. A good example of this is state and country fields. If you type "al", you would expect it to match "Alabama" and "Alaska", but not "California".

I found that the element select has an option for a filter method, which is simply passed the filter text. Technically we could use this to satisfy the requirement, but it would mean re-implementing the filtering logic, and doing the actual filtering differently than what element does internally (i.e. we'd have to filter out the options that are passed to the element component as props). Since I wasn't sure what the side-effects of doing that might be, and this approach is much simpler and avoids duplication, I decided to go with the option of updating element to support a filter mode ("contains" or "startsWith").

### CODE REVIEW

**Comment by tskimmett** [comment]
The change looks nice and simple. The only input I have is that I don't love the names `startsWith` and `contains`, but I'm not sure if I can come up with something better :P. Maybe this?
```js
filterMode: 'matchBeginning` | `matchAnywhere`
```

**Comment by mattheyan** [comment]
Yeah, I didn't give it much thought TBH. They're basically the names of methods in .NET and JS (at least `startsWith`).

**Comment by mattheyan** [comment]
What I mean is that's probably why I picked those...subconsciously.
I like the "beginning" and "anywhere" terminology. But the "match" part seems redundant. 🤔
Just out of curiosity, what is it about the names that you don't like?
And another option: since the project is a JavaScript one, what do you think about following the names of the JS methods: `startsWith` and `includes`? I kind of like the fact that it would be familiar to a JS developer. But, on the other hand, that's not actually what its doing (its actually a case-insensitive search).

**Comment by mattheyan** [comment]
FWIW, the (relevant) existing props are `filterable` and `filterMethod`. What about `filterMatch: "beginning" or "anywhere"`? Or, `filterMatchAnywhere: true` (default: `true`), or something along those lines?

**Comment by tskimmett** [comment]
I like `filterMatch: "beginning" or "anywhere"` 👍

**Comment by mattheyan** [comment]
Done!

**Review by tskimmett — APPROVED** [review]

**Pull request merged**
