### PR TITLE
Standardize class names.

### PR DESCRIPTION
**Pull request by tylertrotter**
This PR standardizes Element's class names where they fall short. See this bug for details: https://cognitoforms.visualstudio.com/Cognito%20Forms/_workitems/edit/16420/

### CODE REVIEW

**Comment by tskimmett** [comment]
@tylertrotter Are these classes not actually used in CSS anywhere? I didn't see any updates to CSS which is why I ask.

**Comment by tylertrotter** [comment]
They're used in Element's CSS, but since we don't use Element's CSS I didn't change them. I updated our CSS in the corresponding "Clean up" PR in devops. You think I should update Element's CSS in this PR? I don't mind doing it. If felt weird not doing it but then it felt futile doing it, so I just opted not to worry about it.

**Comment by tskimmett** [comment]
I think it's kind of weird to change the classes in the components, and leave the old classes in the CSS. That CSS is effectively doing nothing now right, because there aren't any elements using the old classes?

**Comment by tylertrotter** [comment]
What do you think of just deleting the `theme-chalk` folder in this repo since we're not using it?

**Comment by tskimmett** [comment]
I'd rather not delete it. Find/replace of the altered class names should be fine right?

**Comment by tylertrotter** [comment]
Yeah, no problem.

**Comment by tylertrotter** [comment]
@tskimmett, I fixed this PR. I also realized I messed up several tests with these class name changes and fixed those. While I was doing so, I noticed their tests launch "ChromeHeadless" and they use `GetComputedStyle` in some of their tests. Their tests don't seem to take too terribly long. I don't know all the implications but it seems like we could have a lot more flexibility with a headless version of chrome as opposed to jsdom.

image

**Comment by mattheyan** [comment]
I know not being able to use `getComputedStyle` is a limitation of our testing. So, definitely something to look into. But, for what its worth, I had trouble running the tests the last time I tried. And it did seem to me like they were kind of slow. Maybe we could do it in such a way that tests that need a real browser could use Chrome headless and the ones that didn't could use jsdom. 🤷‍♂️

**Review by tskimmett — APPROVED** [review]

**Pull request merged**
